version: '3.1'

services:
  springboot-app:
    container_name: "rei-do-gado-spring"
    build: .
    image: 'springboot-app'
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
