---
  name: Build and push image spring-boot app to AWS ECR
  on:
    push:
      branches: [ main ]
  jobs:
    build-and-push:
      name: Build and push to ECR
      runs-on: ubuntu-18.04
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          run: |
            echo "primeiro checkout"

        - name: Configure AWS Credendials
          uses: aws-actions/configure-AWS-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1
          run: |
            echo "AWS credencias"

        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1
          run: |
            echo "login AWS"

        - name: Build, Tag, and Push the image to Amazon ECR
          id: build-image
          env:
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            ECR_REPOSITORY: rei-do-gado
            IMAGE_TAG: latest
          run: |
            echo "listagem na pasta:"
            la -a
            echo "docker build:"
            docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG